version: '3.8'

services:
  cbcf-namf-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CBCF_AMF_BASE_URL=http://amf-service:8081/amf
    networks:
      - cbcf-network

  # Mock AMF service for testing
  mock-amf:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - cbcf-network

networks:
  cbcf-network:
    driver: bridge
